name: Deployment

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  publish:
    if: ${{ !(github.event_name == 'push') || contains(github.event.head_commit.message, '[deploy]') }}
    runs-on: ubuntu-latest
    env:
      GH_REPO: ${{ github.repository }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - uses: julia-actions/setup-julia@v1
      with:
        version: '1.9'

    - name: Store latest release info
      run: gh release view > last.txt

    - name: Run data curation routines
      run: julia $GITHUB_WORKSPACE/.github/workflows/script.jl

    - name: Retrieve git tree hash
      run: |
        GIT_TREE_HASH="$(cat tree.hash)"
        echo "GIT_TREE_HASH=$GIT_TREE_HASH" >> $GITHUB_ENV

    - name: Retrieve next release tag
      run: |
        TAG="$(cat next.tag)"
        echo "TAG=$TAG" >> $GITHUB_ENV

    - name: Compute SHA256 for the compressed tarball
      run: |
        SHA_256="$(sha256sum -z dist/collections.tar.gz | cut -d " " -f 1)"
        echo "SHA_256=$SHA_256" >> $GITHUB_ENV

    - name: Write release title
      run: |
        TITLE="QUBOInstancesData.jl $TAG"
        echo "TITLE=$TITLE" >> $GITHUB_ENV

    - name: Write release notes
      run: envsubst < "$GITHUB_WORKSPACE/.github/workflows/NOTES.md" > "$RUNNER_TEMP/NOTES.md"

    - name: Publish release
      run: >
        gh release create $TAG
        --latest
        --notes-file "$RUNNER_TEMP/NOTES.md"
        --title "$TITLE"
        --target $GITHUB_SHA
        dist/collections.tar.gz

    - name: Update Documentation
      run: |
        git config --global user.name  "GitHub Actions"
        git config --global user.email "pedromxavier@users.noreply.github.com"
        git add "./*README.md"
        git commit --allow-empty -m "Update Documentation"
        git push
